# Generated by Django 4.2.3 on 2023-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmaaluno',
            name='situacao_aluno',
            field=models.CharField(choices=[('Aprovado', 'APROVADO'), ('Reprovado', 'REPROVADO'), ('Matriculado', 'MATRICULADO'), ('Dispensado', 'DISPENSADO'), ('Cancelado', 'CANCELADO')], max_length=15, verbose_name='Situação do Aluno'),
        ),
    ]
