# Generated by Django 4.2.3 on 2023-07-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_turmaaluno_situacao_aluno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TurmaAluno',
            new_name='Matricula',
        ),
    ]
